# Generated by Django 2.1.7 on 2019-04-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20190409_1532'),
        ('user_management', '0002_auto_20190405_1223'),
    ]

    operations = [
    ]
