# Generated by Django 2.1.3 on 2019-04-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user_management', '0005_auto_20190411_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_group',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initialgroup', to='auth.Group'),
        ),
    ]
