# Generated by Django 2.1.3 on 2019-04-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20190411_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
