# Generated by Django 2.1.3 on 2019-04-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_auto_20190417_1054'),
        ('company_management', '0006_merge_20190409_1840'),
        ('user_management', '0008_auto_20190416_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_management.Company')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
