# Generated by Django 2.1.3 on 2019-01-24 06:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
        ('company_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=6)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('resolution_time', models.DateTimeField(auto_now=True, null=True)),
                ('reopen_time', models.DateTimeField(auto_now=True, null=True)),
                ('close_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.UserTeamMember')),
                ('creator', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='incident_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Incident')),
            ],
            options={
                'db_table': 'incident_attachment',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Incident')),
            ],
            options={
                'db_table': 'incident_comment',
            },
        ),
        migrations.CreateModel(
            name='IncidentCommentAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.IncidentComment')),
            ],
            options={
                'db_table': 'incident_comment_attachment',
            },
        ),
        migrations.CreateModel(
            name='IncidentCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.IncidentComment')),
            ],
            options={
                'db_table': 'incident_comment_reply',
            },
        ),
        migrations.CreateModel(
            name='IncidentCommentReplyAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.IncidentCommentReply')),
            ],
            options={
                'db_table': 'incident_comment_reply_attachment',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='New', max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('actual_startdate', models.DateField(blank=True, null=True)),
                ('actual_enddate', models.DateField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enddate'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Milestone')),
            ],
            options={
                'db_table': 'milestone_attachment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(choices=[('New', 'New'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Terminated', 'Terminated')], default='New', max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('project_code', models.CharField(default='JB/00/00', max_length=20)),
                ('estimated_cost', models.FloatField(default=0.0)),
                ('final_cost', models.FloatField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('actual_startdate', models.DateField(blank=True, null=True)),
                ('actual_enddate', models.DateField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='company_management.Company')),
                ('creator', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('project_assignee', models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('project_team', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user_management.UserTeam')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendor', to='company_management.Company')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_attachment',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='documents/projects/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project')),
            ],
            options={
                'db_table': 'project_forum',
            },
        ),
        migrations.CreateModel(
            name='ProjectForumMessageAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_forum_message_attachments',
            },
        ),
        migrations.CreateModel(
            name='ProjectForumMessageReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_forum_message_replies',
            },
        ),
        migrations.CreateModel(
            name='ProjectForumMessageReplyAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('projectforummessagereply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.ProjectForumMessageReplies')),
            ],
            options={
                'db_table': 'project_forum_message_reply_attachments',
            },
        ),
        migrations.CreateModel(
            name='ProjectForumMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('projectforum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.ProjectForum')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.UserTeamMember')),
            ],
            options={
                'db_table': 'project_forum_messages',
            },
        ),
        migrations.CreateModel(
            name='ProjectsHasCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company_management.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project')),
            ],
            options={
                'db_table': 'projects_has_companies',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('backup', 'backup'), ('visitor', 'visitor')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.ProjectTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='Open', max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(blank=True, max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Task')),
            ],
            options={
                'db_table': 'task_attachment',
            },
        ),
        migrations.AddField(
            model_name='projectforummessagereplies',
            name='projectforummessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.ProjectForumMessages'),
        ),
        migrations.AddField(
            model_name='projectforummessagereplies',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.UserTeamMember'),
        ),
        migrations.AddField(
            model_name='projectforummessageattachments',
            name='projectforummessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.ProjectForumMessages'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project'),
        ),
        migrations.AddField(
            model_name='incident',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Milestone'),
        ),
        migrations.AddField(
            model_name='incident',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Project'),
        ),
        migrations.AddField(
            model_name='incident',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.Task'),
        ),
    ]
