# Generated by Django 2.1.3 on 2019-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190514_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='chat_room_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
