# Generated by Django 2.1.3 on 2019-05-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_directchat_chat_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
