# Generated by Django 2.1.3 on 2019-05-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190516_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='directchat',
            name='chat_room_id',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
