# Generated by Django 2.1.3 on 2019-04-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=45)),
                ('contact_value', models.CharField(max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_management.Branch')),
            ],
            options={
                'db_table': 'branch_contact',
            },
        ),
        migrations.RemoveField(
            model_name='branchemailaddresses',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchphonecontacts',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ManyToManyField(to='company_management.Branch'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ManyToManyField(to='company_management.Company'),
        ),
        migrations.DeleteModel(
            name='BranchEmailAddresses',
        ),
        migrations.DeleteModel(
            name='BranchPhoneContacts',
        ),
        migrations.DeleteModel(
            name='CompanyDepartment',
        ),
    ]
