# Generated by Django 2.1.3 on 2019-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0002_auto_20190405_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
