# Generated by Django 2.1.3 on 2019-04-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0002_auto_20190408_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhoneContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=45)),
                ('secondary_number', models.CharField(blank=True, max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_management.Branch')),
            ],
            options={
                'db_table': 'branch_phone_contact',
            },
        ),
    ]
