# Generated by Django 2.1.3 on 2019-04-09 07:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0003_auto_20190408_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydomain',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
