# Generated by Django 2.1.7 on 2019-04-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0003_branchphonecontact'),
        ('company_management', '0005_auto_20190409_1100'),
    ]

    operations = [
    ]
